{% set name = "atlantis" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: src/github.com/runatlantis/{{ name }}
    url: https://github.com/runatlantis/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: d163c9aa0d17be5e5b90fdc919a6aba881c1f24869dff30cbe1c112bcc2c2c9c

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('go') }}
    - git

test:
  commands:
    - {{ name|lower }} version

about:
  home: https://www.runatlantis.io
  license: Apache 2.0
  summary: A self-hosted golang application that listens for Terraform pull request events via webhooks.
  description: |
    Runs terraform plan and apply remotely and comments back on the pull request with the output.
  doc_url: https://www.runatlantis.io/docs
  dev_url: https://github.com/runatlantis/atlantis

extra:
  recipe-maintainers:
    - sodre
