{% set name = "atlantis" %}
{% set version = "0.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: src/github.com/runatlantis/{{ name }}
    url: https://github.com/runatlantis/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: 26304b0510544ec883f0bb08f7c60794062b4930e6cbaa3396f6d0e66aa813e0

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('go') }}
    - git

test:
  commands:
    - {{ name|lower }} version

about:
  home: https://www.runatlantis.io
  license: Apache 2.0
  summary: A self-hosted golang application that listens for Terraform pull request events via webhooks.
  description: |
    Runs terraform plan and apply remotely and comments back on the pull request with the output.
  doc_url: https://www.runatlantis.io/docs
  dev_url: https://github.com/runatlantis/atlantis

extra:
  recipe-maintainers:
    - sodre
