# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "J6beHE6qLlAfzbBzgYYIr9JHYXCQqL0+HttnP60zS7StbXqvapa3o4NA8WjpshhWRXROKhXiAwNSp/pva/2thRyhp8TT+cHY4oUJakYkNecJO+rhAO1iCySq+kfo3Do9aIGySBnp0m6dMW+ycAcoZyKCaiJIHT8x89nZB5ws2igi6V3s/0OPGKpp5QWMGqgrBgkitp2pgAXdw+Xv4HXpN1+a4wLS2aB8Y2Nvmmf7cvy5FsUPrdGmC8SP2I6HPTEm2Oo0mR9dQe6ht8/EpNNAfCS8o1hEwyiyEfQo4yimFahxvXTXF7rqJJrgBe9xqqCc0xZJm3ZyfeYFkd5XErZAD3vOADZ6MIH40azg2obtKnyJAvGYsYaYKP4EgG5c/krD59saEOT0g5FWHsl/cpP1EbU5/mlM0pjwz3Oh/5M+kQbjao5sgaexHVEe4X8Y//cOpYnzDkdYE966pyWiJTAe1z7HEDAnFxeb/q0lGtjCC9GH8URs5mAGGh1S+g/qaAS3jeUdVihfSFRg8IEW8fnGmgnkohC7IAbIZljB8vIrogg1iWUZ+mJAbRpQtqrImWxRiJxFsj2NRUOT30FORBQ2J9dwt6E9GtnR6rFtcfUdw1elIXiuPvCmcIx+OweX9ElTYRiZ/VbNQFXNtqPh13JIw4n1VN2dof2iEC4jqh0/n2Y="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2 conda-build
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  -  conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml