appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: J6beHE6qLlAfzbBzgYYIr9JHYXCQqL0+HttnP60zS7StbXqvapa3o4NA8WjpshhWRXROKhXiAwNSp/pva/2thRyhp8TT+cHY4oUJakYkNecJO+rhAO1iCySq+kfo3Do9aIGySBnp0m6dMW+ycAcoZyKCaiJIHT8x89nZB5ws2igi6V3s/0OPGKpp5QWMGqgrBgkitp2pgAXdw+Xv4HXpN1+a4wLS2aB8Y2Nvmmf7cvy5FsUPrdGmC8SP2I6HPTEm2Oo0mR9dQe6ht8/EpNNAfCS8o1hEwyiyEfQo4yimFahxvXTXF7rqJJrgBe9xqqCc0xZJm3ZyfeYFkd5XErZAD3vOADZ6MIH40azg2obtKnyJAvGYsYaYKP4EgG5c/krD59saEOT0g5FWHsl/cpP1EbU5/mlM0pjwz3Oh/5M+kQbjao5sgaexHVEe4X8Y//cOpYnzDkdYE966pyWiJTAe1z7HEDAnFxeb/q0lGtjCC9GH8URs5mAGGh1S+g/qaAS3jeUdVihfSFRg8IEW8fnGmgnkohC7IAbIZljB8vIrogg1iWUZ+mJAbRpQtqrImWxRiJxFsj2NRUOT30FORBQ2J9dwt6E9GtnR6rFtcfUdw1elIXiuPvCmcIx+OweX9ElTYRiZ/VbNQFXNtqPh13JIw4n1VN2dof2iEC4jqh0/n2Y=}
conda_forge_output_validation: true
